apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: individual-mysecret
  namespace: config-demo
spec:
  refreshInterval: 15s
  secretStoreRef:
	name: {{ .Values.secretStore.name }}
	kind: {{ .Values.secretStore.kind }}
  data:
  - secretKey: fooSecret
	remoteRef:
  	key: secret/data/global/mysecret
  	property: foo
  - secretKey: barSecret
	remoteRef:
  	key: secret/data/global/mysecret
  	property: bar
  target:
	  name: individual-mysecret
	template:
  	type: Opaque
  	data:
    	baz: |-
      	{{ "{{ .fooSecret }}" }}
    	boz: |-
      	{{ "{{ .barSecret }}" }}